In [1]:
import sqlite3
import pandas as pd

In [2]:
sql = '''
    SELECT a.page_code
        , page_name
        , page_release
        , b.case_code
        , case_name
        , case_release
        , child_case_code
        , child_case_desc
    FROM page a
        , use_case b
        , child_case c
    WHERE a.page_code = b.page_code
        AND b.page_code = c.page_code
        AND b.case_code = c.case_code
        AND case_release = '0.2'
'''

df = pd.read_sql(sql, con=sqlite3.connect('axure.db'))

In [3]:
df

,page_code,page_name,page_release,case_code,case_name,case_release,child_case_code,child_case_desc
0,B-0,页面名称,0.2,N1,普通用例名称,0.2,N1-1,普通子用例说明
1,B-0,页面名称,0.2,N1,普通用例名称,0.2,N1-2,普通子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
2,B-0,页面名称,0.2,N1,普通用例名称,0.2,N1-3,普通子用例说明
3,B-0,页面名称,0.2,E1,异常用例名称,0.2,E1-1,异常子用例说明
4,B-0,页面名称,0.2,E1,异常用例名称,0.2,E1-2,异常子用例说明，包括：- 这里是具体的说明- 这里是具体的说明

In [4]:
pd.read_sql('SELECT * FROM page', con=sqlite3.connect('axure.db'))

,page_id,page_code,page_name,page_release,scene,page_desc,page_note
0,1,A-0,页面名称,0,用户场景：用户进入该页面的场景,功能描述：页面的功能,补充说明：需求的补充说明
1,2,B-0,页面名称,0.2,用户场景：用户进入该页面的场景,功能描述：页面的功能,补充说明：需求的补充说明

In [5]:
pd.read_sql('SELECT * FROM use_case', con=sqlite3.connect('axure.db'))

   case_id page_code case_code case_name case_release case_note case_type
0        1       A-0        N1    普通用例名称            0              normal
1        2       A-0        N2    普通用例名称            0     这里是备注    normal
2        3       A-0        E1    异常用例名称            0            abnormal
3        4       A-0        D1      数据逻辑            0               logic
4        5       B-0        N1    普通用例名称          0.2              normal
5        6       B-0        N2    普通用例名称            0     这里是备注    normal
6        7       B-0        E1    异常用例名称          0.2            abnormal
7        8       B-0        D1      数据逻辑            0               logic

In [6]:
pd.read_sql('SELECT * FROM child_case', con=sqlite3.connect('axure.db'))

,child_case_id,page_code,case_code,child_case_code,child_case_desc
0,1,A-0,N1,N1-1,普通子用例说明
1,2,A-0,N1,N1-2,普通子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
2,3,A-0,N1,N1-3,普通子用例说明
3,4,A-0,N2,N2-1,普通子用例说明
4,5,A-0,N2,N2-2,普通子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
5,6,A-0,N2,N2-3,普通子用例说明，普通子用例说明，普通子用例说明
6,7,A-0,E1,E1-1,异常子用例说明
7,8,A-0,E1,E1-2,异常子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
8,9,A-0,D1,D1-1,排序规则
9,10,A-0,D1,D1-2,状态变更规则
10,11,A-0,D1,D1-3,字段说明，包括：- 这里是具体说明- 这里是具体说明
11,12,B-0,N1,N1-1,普通子用例说明
12,13,B-0,N1,N1-2,普通子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
13,14,B-0,N1,N1-3,普通子用例说明
14,15,B-0,N2,N2-1,普通子用例说明
15,16,B-0,N2,N2-2,普通子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
16,17,B-0,N2,N2-3,普通子用例说明，普通子用例说明，普通子用例说明
17,18,B-0,E1,E1-1,异常子用例说明
18,19,B-0,E1,E1-2,异常子用例说明，包括：- 这里是具体的说明- 这里是具体的说明
19,20,B-0,D1,D1-1,排序规则
20,21,B-0,D1,D1-2,状态变更规则
21,22,B-0,D1,D1-3,字段说明，包括：- 这里是具体说明- 这里是具体说明